BUILD: Include gp_rpc_debug.h into tarball
New header file was introduced in the commit
fdcad4fa9696c5f501b16d1b3f622ccc28b6147f
but it was not properly added to makefile
and therefore it was not included into tarball.
And build will fail from tarball due to missing header.

gssproxy-0.4.1/tests/cli_srv_comm.c:17:0: <--[gcc]
gssproxy-0.4.1/src/gp_rpc_process.h:18:26: fatal error: gp_rpc_debug.h: No such file or directory <--[gcc]
 #include "gp_rpc_debug.h"
                          ^
compilation terminated.
Makefile:1267: recipe for target 'tests/cli_srv_comm.o' failed

Signed-off-by: Lukas Slebodnik <lslebodn@redhat.com>
Reviewed-by: Simo Sorce <simo@redhat.com>